---
title: "Confounding"
format: html
editor: visual
---
```{r}
library(nnet)
```

```{r}
# Construct a data frame containing sleep, macronutrient and demographic data
data_confounding <- left_join(sleep, diet_total, by = "SEQN")
data_confounding <- left_join(data_confounding, demo, by = "SEQN")
data_confounding <- data_confounding %>%
  select(SEQN, #identifier
         SLD012, SLD013, SLQ050, SLQ120, #sleep questions: weekday hrs, weeknd hr, doctor question, overly sleepy?
         WTDRD1, DR1DRSTZ, #dietary weight and dietary recall status
         DR1TKCAL, DR1TPROT, DR1TCARB, DR1TSUGR, DR1TFIBE, DR1TTFAT, #diet
         RIAGENDR, RIDAGEYR, RIDRETH1, RIDRETH3, #gender, age in yrs, ethnicity, ethnicity w/ NH Asian
         DMDBORN4, #born in US?
         DMDMARTL, #Marital status, household ref. of martial status
         DMDHHSIZ, DMDHHSZA, # of people in HH and # of children 5 years or younger in HH
         DMDHHSZB, # of children 6-17 years old in HH
         DMDHHSZE, # of adults 60 years or older in HH
         INDHHIN2, INDFMIN2, INDFMPIR #Annual household income, annual family income, and ratio of family income to poverty
  )

# data preprocessing
data_confounding$SLQ050[data_confounding$SLQ050 == 9] <- NA
data_confounding$SLQ120[data_confounding$SLQ120 == 9] <- NA
data_confounding$DR1DRSTZ[data_confounding$DR1DRSTZ == 2] <- NA
data_confounding$DMDBORN4[data_confounding$DMDBORN4 == 77] <- NA
data_confounding$DMDBORN4[data_confounding$DMDBORN4 == 99] <- NA
data_confounding$DMDMARTL[data_confounding$DMDMARTL == 77] <- NA
data_confounding$DMDMARTL[data_confounding$DMDMARTL == 99] <- NA
data_confounding$INDHHIN2[data_confounding$INDHHIN2 == 77] <- NA
data_confounding$INDHHIN2[data_confounding$INDHHIN2 == 99] <- NA
data_confounding$INDFMIN2[data_confounding$INDFMIN2 == 77] <- NA
data_confounding$INDFMIN2[data_confounding$INDFMIN2 == 99] <- NA
data_confounding$INDFMPIR[data_confounding$INDFMPIR == 77] <- NA
data_confounding$INDFMPIR[data_confounding$INDFMPIR == 99] <- NA

data_confounding <- data_confounding %>% mutate(DMDBORN4 = as.factor(DMDBORN4), DMDMARTL = as.factor(DMDMARTL), RIDRETH1 = as.factor(RIDRETH1), RIDRETH3 = as.factor(RIDRETH3))
```

```{r}
# Explore associations between demographics and sleep outcome SLD012 (sleep duration on weekdays)

temp <- data_confounding %>% select(-SEQN,-SLD013,-SLQ050,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TCARB, -DR1TFIBE, -DR1TKCAL, -DR1TSUGR, -DR1TTFAT, -DR1TPROT) 
weights <- data_confounding %>% pull(WTDRD1)

confounding_model.SLD012 <- lm(SLD012 ~ ., data = temp, weights = weights)
summary(confounding_model.SLD012)
```

```{r}
# Explore associations between demographics and sleep outcome SLD012 (sleep duration on weekends)

temp <- data_confounding %>% select(-SEQN,-SLD012,-SLQ050,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TCARB, -DR1TFIBE, -DR1TKCAL, -DR1TSUGR, -DR1TTFAT, -DR1TPROT)
confounding_model.SLD013 <- lm(SLD013 ~ ., data = temp, weights = weights)
summary(confounding_model.SLD013)
```

```{r}
# Explore associations between demographics and sleep outcome SLQ050 (telling your doctor about sleeping problems)
temp <- data_confounding %>% select(-SEQN,-SLD012,-SLD013,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TCARB, -DR1TFIBE, -DR1TKCAL, -DR1TSUGR, -DR1TTFAT, -DR1TPROT)

temp <- temp %>% 
  filter(SLQ050 != 9) %>% 
  mutate(SLQ050 = as.numeric(SLQ050) - 1)

confounding_model.SLQ050 <- glm(SLQ050 ~ ., data = temp, family = "binomial")
summary(confounding_model.SLQ050)
```

```{r}
# Explore associations between demographics and sleep outcome SLQ120 (how many times a month they feel overly sleepy)
temp <- data_confounding %>% select(-SEQN,-SLD012,-SLD013,-SLQ050, -WTDRD1, -DR1DRSTZ, -DR1TCARB, -DR1TFIBE, -DR1TKCAL, -DR1TSUGR, -DR1TTFAT, -DR1TPROT)

temp <- temp %>% 
  filter(SLQ120 %in% c(0,1,2,3,4)) 

confounding_model.SLQ120 <- multinom(SLQ120 ~ ., data = temp)
#summary(confounding_model.SLQ120)

summ.MNfit <- function(fit, digits=3){
  s <- summary(fit)
  for(i in 2:length(fit$lev))
    {
    ##
    cat("\nLevel", fit$lev[i], "vs. Level", fit$lev[1], "\n")
    ##
    betaHat <- s$coefficients[(i-1),]
    se <- s$standard.errors[(i-1),]
    zStat <- betaHat / se
    pval <- 2 * pnorm(abs(zStat), lower.tail=FALSE)
    ##
    RRR <- exp(betaHat)
    RRR.lower <- exp(betaHat - qnorm(0.975)*se)
    RRR.upper <- exp(betaHat + qnorm(0.975)*se)
    ##
    results <- cbind(betaHat, se, pval, RRR, RRR.lower, RRR.upper)
    print(round(results, digits=digits))
    }
}
summ.MNfit(confounding_model.SLQ120)
```

```{r}
# Explore associations between demographics and kcal predictor DR1TKCAL

temp <- data_confounding %>% select(-SEQN,-SLD012, -SLD013,-SLQ050,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TCARB, -DR1TFIBE, -DR1TSUGR, -DR1TTFAT, -DR1TPROT)
weights <- data_confounding %>% pull(WTDRD1)

confounding_model.DR1TKCAL <- lm(DR1TKCAL ~ ., data = temp, weights = weights)
summary(confounding_model.DR1TKCAL)
```

```{r}
# Explore associations between demographics and carb predictor DR1TCARB

temp <- data_confounding %>% select(-SEQN,-SLD012, -SLD013,-SLQ050,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TKCAL, -DR1TFIBE, -DR1TSUGR, -DR1TTFAT, -DR1TPROT)
weights <- data_confounding %>% pull(WTDRD1)

confounding_model.DR1TCARB <- lm(DR1TCARB ~ ., data = temp, weights = weights)
summary(confounding_model.DR1TCARB)
```
```{r}
# Explore associations between demographics and prot predictor DR1TPROT

temp <- data_confounding %>% select(-SEQN,-SLD012, -SLD013,-SLQ050,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TKCAL, -DR1TFIBE, -DR1TSUGR, -DR1TTFAT, -DR1TCARB)
weights <- data_confounding %>% pull(WTDRD1)

confounding_model.DR1TPROT <- lm(DR1TPROT ~ ., data = temp, weights = weights)
summary(confounding_model.DR1TPROT)
```

```{r}
# Explore associations between demographics and total fat predictor DR1TTFAT

temp <- data_confounding %>% select(-SEQN,-SLD012, -SLD013,-SLQ050,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TKCAL, -DR1TFIBE, -DR1TSUGR, -DR1TCARB, -DR1TPROT)
weights <- data_confounding %>% pull(WTDRD1)

confounding_model.DR1TTFAT <- lm(DR1TTFAT ~ ., data = temp, weights = weights)
summary(confounding_model.DR1TTFAT)
```

```{r}
# Explore associations between demographics and fiber predictor DR1TFIBE

temp <- data_confounding %>% select(-SEQN,-SLD012, -SLD013,-SLQ050,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TKCAL, -DR1TCARB, -DR1TSUGR, -DR1TTFAT, -DR1TPROT)
weights <- data_confounding %>% pull(WTDRD1)

confounding_model.DR1TFIBE <- lm(DR1TFIBE ~ ., data = temp, weights = weights)
summary(confounding_model.DR1TFIBE)
```

```{r}
# Explore associations between demographics and sugar predictor DR1TSUGR

temp <- data_confounding %>% select(-SEQN,-SLD012, -SLD013,-SLQ050,-SLQ120, -WTDRD1, -DR1DRSTZ, -DR1TKCAL, -DR1TCARB, -DR1TFIBE, -DR1TTFAT, -DR1TPROT)
weights <- data_confounding %>% pull(WTDRD1)

confounding_model.DR1TSUGR <- lm(DR1TSUGR ~ ., data = temp, weights = weights)
summary(confounding_model.DR1TSUGR)
```

```{r}
# Operational check for gender confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR)
weights <- data_confounding %>% pull(WTDRD1)

confounding_model.op_reduced <- lm(SLD012~ ., data = temp, weights = weights)

temp <- temp %>% mutate(RIAGENDR = data_confounding$RIAGENDR)
confounding_model.op_RIAGENDR <- lm(SLD012~ ., data = temp, weights = weights)

original_coefficients <- confounding_model.op_reduced$coefficients[2:7]

adjusted_coefficients <-  confounding_model.op_RIAGENDR$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```

```{r}
# Operational check for age confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR, RIDAGEYR)

confounding_model.op_RIAGENDR <- lm(SLD012~ ., data = temp, weights = weights)

adjusted_coefficients <-  confounding_model.op_RIAGENDR$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```

```{r}
# Operational check for race confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR, RIDRETH1)

confounding_model.op_RIDRETH1 <- lm(SLD012~ ., data = temp, weights = weights)

adjusted_coefficients <-  confounding_model.op_RIDRETH1$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```

```{r}
# Operational check for born in the US confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR, DMDBORN4)

confounding_model.op_DMDBORN4 <- lm(SLD012~ ., data = temp, weights = weights)

adjusted_coefficients <-  confounding_model.op_DMDBORN4$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```

```{r}
# Operational check for marital status confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR, DMDMARTL)

confounding_model.op_DMDMARTL <- lm(SLD012~ ., data = temp, weights = weights)

adjusted_coefficients <-  confounding_model.op_DMDMARTL$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```

```{r}
# Operational check for household size confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR, DMDHHSIZ)

confounding_model.op_DMDHHSIZ <- lm(SLD012~ ., data = temp, weights = weights)

adjusted_coefficients <-  confounding_model.op_DMDHHSIZ$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```

```{r}
# Operational check for number of child under 5 confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR, DMDHHSZA)

confounding_model.op_DMDHHSZA <- lm(SLD012~ ., data = temp, weights = weights)

adjusted_coefficients <-  confounding_model.op_DMDHHSZA$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```

```{r}
# Operational check for household income confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR, INDHHIN2)

confounding_model.op_INDHHIN2 <- lm(SLD012~ ., data = temp, weights = weights)

adjusted_coefficients <-  confounding_model.op_INDHHIN2$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```

```{r}
# Operational check for number of child under 5 confounding
temp <- data_confounding %>% select(SLD012, DR1TKCAL, DR1TCARB, DR1TFIBE, DR1TTFAT, DR1TPROT, DR1TSUGR, INDFMPIR)

confounding_model.op_INDFMPIR <- lm(SLD012~ ., data = temp, weights = weights)

adjusted_coefficients <-  confounding_model.op_INDFMPIR$coefficients[2:7]

100 * (original_coefficients - adjusted_coefficients) / original_coefficients
```