```{r}
library(broom)
library(ggplot2)
library(nnet)
library(splitstackshape)
library(ResourceSelection)
#library(LogisticDx)
library(survival)
#library(DescTools)
library(car)
```

```{r}
# Construct a data frame containing sleep, macronutrient and demographic data
data_confounding <- left_join(sleep, diet_total, by = "SEQN")
data_confounding <- left_join(data_confounding, demo, by = "SEQN")
data_confounding <- data_confounding %>%
  select(SEQN, #identifier
         SLD012, SLD013, SLQ050, SLQ120, #sleep questions: weekday hrs, weeknd hr, doctor question, overly sleepy?
         WTDRD1, DR1DRSTZ, #dietary weight and dietary recall status
         DR1TKCAL, DR1TPROT, DR1TCARB, DR1TSUGR, DR1TFIBE, DR1TTFAT, #diet
         RIAGENDR, RIDAGEYR, RIDRETH1, RIDRETH3, #gender, age in yrs, ethnicity, ethnicity w/ NH Asian
         DMDBORN4, #born in US?
         DMDMARTL, #Marital status, household ref. of martial status
         DMDHHSIZ, DMDHHSZA, # of people in HH and # of children 5 years or younger in HH
         DMDHHSZB, # of children 6-17 years old in HH
         DMDHHSZE, # of adults 60 years or older in HH
         INDHHIN2, INDFMIN2, INDFMPIR #Annual household income, annual family income, and ratio of family income to poverty
  )

# data preprocessing
data_confounding$SLQ050[data_confounding$SLQ050 == 9] <- NA
data_confounding$SLQ120[data_confounding$SLQ120 == 9] <- NA
data_confounding$DR1DRSTZ[data_confounding$DR1DRSTZ == 2] <- NA
data_confounding$DMDBORN4[data_confounding$DMDBORN4 == 77] <- NA
data_confounding$DMDBORN4[data_confounding$DMDBORN4 == 99] <- NA
data_confounding$DMDMARTL[data_confounding$DMDMARTL == 77] <- NA
data_confounding$DMDMARTL[data_confounding$DMDMARTL == 99] <- NA
data_confounding$INDHHIN2[data_confounding$INDHHIN2 == 77] <- NA
data_confounding$INDHHIN2[data_confounding$INDHHIN2 == 99] <- NA
data_confounding$INDFMIN2[data_confounding$INDFMIN2 == 77] <- NA
data_confounding$INDFMIN2[data_confounding$INDFMIN2 == 99] <- NA
data_confounding$INDFMPIR[data_confounding$INDFMPIR == 77] <- NA
data_confounding$INDFMPIR[data_confounding$INDFMPIR == 99] <- NA

data_confounding <- data_confounding %>% mutate(DMDBORN4 = as.integer(DMDBORN4) - 1, DMDMARTL = as.factor(DMDMARTL), RIDRETH1 = as.factor(RIDRETH1), RIDRETH3 = as.factor(RIDRETH3), SLQ050 = as.numeric(SLQ050) - 1)
```

```{r}
# Explore proportional odds assumption for unadjusted model

# Proportional odds are NOT satisfied

# Preprocess data  and create indicators with dichotomous cutoffs
temp <- data_confounding %>% select(SLQ120, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT) %>%
  mutate(indicator1234 = as.integer(SLQ120 > 0), 
         indicator234 = as.integer(SLQ120 > 1),
         indicator34 = as.integer(SLQ120 > 2),
         indicator4 = as.integer(SLQ120 > 3))

temp1234 <- temp %>% select(indicator1234, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT) %>% na.omit()
```

```{r}
# Create models using different cutoffs for the outcome
proportional.odds1234 <- glm(indicator1234 ~ ., data = temp1234, family = "binomial")

temp234 <- temp %>% select(indicator234, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT) %>% 
  na.omit()

proportional.odds234 <- glm(indicator234 ~ ., data = temp234, family = "binomial")

temp34 <- temp %>% select(indicator34, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT) %>% 
  na.omit()

proportional.odds34 <- glm(indicator34 ~ ., data = temp34, family = "binomial")

temp4 <- temp %>% select(indicator4, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT) %>% 
  na.omit()

proportional.odds4 <- glm(indicator4 ~ ., data = temp4, family = "binomial")
```

```{r}
# Function to extract coefficients and confidence intervals
get_coef_ci <- function(model, group) {
  tidy_model <- tidy(model, conf.int = TRUE)
  coef_ci <- tidy_model[-1, c("term", "estimate", "conf.low", "conf.high")]
  coef_ci$group <- group
  return(coef_ci)
}

# Extract coefficients and confidence intervals for each model
coef_ci_1234 <- get_coef_ci(proportional.odds1234, "I(X>0): Rarely or more")
coef_ci_234 <- get_coef_ci(proportional.odds234, "I(X>1): Sometimes or more")
coef_ci_34 <- get_coef_ci(proportional.odds34, "I(X>2): Often or Almost Always")
coef_ci_4 <- get_coef_ci(proportional.odds4, "I(X>3): Almost Always")

all_coef_ci <- rbind(coef_ci_1234, coef_ci_234, coef_ci_34, coef_ci_4)

# Create a plot
proportional.odds.plot <- ggplot(all_coef_ci, aes(x = term, y = estimate, ymin = conf.low, ymax = conf.high, group = group, color = group)) +
  geom_point(position = position_dodge(width = 0.5), size = 2) +
  geom_errorbar(position = position_dodge(width = 0.5), width = 0.2) +
  labs(title = "Slope Estimates and 95% Confidence Intervals",
       subtitle = "In the past month, how often did you feel overly sleepy during the day?",
       x = "Predictors",
       y = "Estimates") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


proportional.odds.plot
```

```{r}

summ.MNfit <- function(fit, digits=5){
  s <- summary(fit)
  for(i in 2:length(fit$lev))
    {
    ##
    cat("\nLevel", fit$lev[i], "vs. Level", fit$lev[1], "\n")
    ##
    betaHat <- s$coefficients[(i-1),1:5]
    se <- s$standard.errors[(i-1),1:5]
    zStat <- betaHat / se
    pval <- 2 * pnorm(abs(zStat), lower.tail=FALSE)
    ##
    RRR <- exp(betaHat)
    RRR.lower <- exp(betaHat - qnorm(0.975)*se)
    RRR.upper <- exp(betaHat + qnorm(0.975)*se)
    ##
    results <- cbind(betaHat, se, pval, RRR, RRR.lower, RRR.upper)
    print(round(results, digits=digits))
    }
}

```

```{r}
# Unadjusted multinomial model for overly sleep outcome
temp <- data_confounding %>% select(SLQ120, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT)

temp <- temp %>% 
  filter(SLQ120 %in% c(0,1,2,3,4)) 

multinom.unadjusted <- multinom(SLQ120 ~ ., data = temp)
#summ = summary(multinom.unadjusted)
summ.MNfit(multinom.unadjusted)
```

```{r}
# Partially adjusted multinomial model for overly sleep outcome
temp <- data_confounding %>% select(SLQ120, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT, RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN4, DMDHHSIZ, DMDHHSZA)

temp <- temp %>% 
  filter(SLQ120 %in% c(0,1,2,3,4)) 

multinom.partially.adjusted <- multinom(SLQ120 ~ ., data = temp)
summ = summary(multinom.partially.adjusted)
summ.MNfit(multinom.partially.adjusted)
```

```{r}
# Fully adjusted multinomial model for overly sleep outcome
temp <- data_confounding %>% select(SLQ120, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT, RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN4, DMDHHSIZ, DMDHHSZA, DMDMARTL, INDFMPIR)

temp <- temp %>% 
  filter(SLQ120 %in% c(0,1,2,3,4)) 

multinom.fully.adjusted <- multinom(SLQ120 ~ ., data = temp)
summ = summary(multinom.fully.adjusted)
summ.MNfit(multinom.fully.adjusted)
```

```{r}
# Unadjusted logistic model for telling a doctor about sleep outcome
temp <- data_confounding %>% select(SLQ050, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT)

logistic.unadjusted <- glm(SLQ050 ~ ., data = temp, family = "binomial")
summary(logistic.unadjusted)
```
```{r}
hist(logistic.unadjusted$fitted, main="p-hats")
#hist(logist(logistic.unadjusted), main="hat-values")

par(mfrow=c(1,1))
influencePlot(logistic.unadjusted,col="red")
residualPlot(logistic.unadjusted)
hoslem.test(logistic.unadjusted$y,fitted(logistic.unadjusted))
```

```{r}
# Partially logistic model for telling a doctor about sleep outcome
temp <- data_confounding %>% select(SLQ050, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT, RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN4, DMDHHSIZ, DMDHHSZA)

logistic.partially.adjusted <- glm(SLQ050 ~ ., data = temp, family = "binomial")
summary(logistic.partially.adjusted)
```

```{r}
# Fully logistic model for telling a doctor about sleep outcome
temp <- data_confounding %>% select(SLQ050, DR1TPROT, DR1TCARB, DR1TFIBE, DR1TTFAT, RIAGENDR, RIDAGEYR, RIDRETH1, DMDBORN4, DMDHHSIZ, DMDHHSZA, DMDMARTL, INDFMPIR)

logistic.fully.adjusted <- glm(SLQ050 ~ ., data = temp, family = "binomial")
summary(logistic.fully.adjusted)
```

